# Generated by Django 3.1.6 on 2021-02-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetracker',
            name='logout_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancetracker',
            name='working_hours_per_day',
            field=models.TimeField(null=True),
        ),
    ]
